version: '3.3'

services:
    mongo:
        container_name: mongodb
        image: mongo:5.0.0
        ports:
            - "27017:27017"
        volumes:
            - mongodbdata:/data/db
        restart: always
       

volumes:
    mongodbdata:

networks:
    default:
        external:
            name: mongo-network
